<a href="https://colab.research.google.com/github/DaPardo/carpetadel13dejul/blob/master/PardoDaniel_S1CASA_IntroPython_01_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PYTHON: INTRODUCCION (O REPASO)

Tutoriales Python:

learnpython.org

https://www.geeksforgeeks.org/python-programming-language/?ref=lbp

https://argentinaenpython.com/quiero-aprender-python/TutorialPython3.pdf

https://www.youtube.com/playlist?list=PLU8oAlHdN5BlvPxziopYZRd55pdqFwkeS

https://www.freecodecamp.org/learn/scientific-computing-with-python/#python-for-everybody



IMPRIMIR EN LA TERMINAL:

In [ ]:
#primer codigo: "hola mundo"
print("hola mundo")



hola mundo


TIPOS DE VARIABLES:

In [ ]:
#enteras
mi_ent=3

#flotates
mi_float=4.0

#boleanas
mi_bol=True

#caracteres
mi_car = "hola"
mi_car2='hola2'

print("variable: ", mi_ent)
print("tipo de variable: ", type(mi_ent))
 #mini ejercicio: impriman las otras variables y su tipo

variable:  3
tipo de variable:  <class 'int'>


OPERACIONES MATEMÁTICAS BÁSICAS

In [ ]:
#operaciones basicas entre variables
suma = mi_ent + mi_float
#print(suma)

suma2= mi_car + " " + mi_car2
#print(suma2)

#	NO FUNCIONA
#suma_que_no_funciona = mi_ent + mi_car
#print(suma_que_no_funciona)

#mini ejercicio: descomenten lo anterior y entiendan cuál es el error

LISTAS y APPEND

In [ ]:
#listas
#defino lista vacia:
mi_lista=[]
#print(mi_lista)

#le agrego un elemento
mi_lista.append(27.0)
#print(mi_lista)

#le agrego otro elemento
mi_lista.append(12)
#print(mi_lista)

#le agrego varios elementos
mi_lista.append(45)
mi_lista.append(5.2)
mi_lista.append(17)
mi_lista.append(22)

print("mi lista: ", mi_lista)

#imprimo el primer elemento de la lista
print("primer elemento: ", mi_lista[0])

#mini ejercicio: imprima el tercer elemento:
print("primer elemento: ", mi_lista[2])

#otra forma de definir listas:
mi_lista2=[12,34,56,67,87,65,45.0]
print("mi_lista2: ", mi_lista2)

#las listas pueden tener todo tipo de variables
mi_lista3=[12, 34.0, "gato", True, 34.56]
print("mi_lista3: ", mi_lista3)

#mini ejercicio: qué pasa si sumo mi_lista2 con mi_lista3? imprima el resultado
mi_suma=mi_lista2 + mi_lista3
print("suma de mi_lista2 y mi_lista3: ", mi_suma)

#mini ejercicio: qué pasa si multiplico mi_lista2 por 3
prod_lista= mi_lista2*3
print("mi_lista2 x 2: ", prod_lista)

#mini ejercicio: qué pasa si multiplico mi_lista por mi_lista2?
#prod_listas = mi_lista*mi_lista2

mi lista:  [27.0, 12, 45, 5.2, 17, 22]
primer elemento:  27.0
primer elemento:  45
mi_lista2:  [12, 34, 56, 67, 87, 65, 45.0]
mi_lista3:  [12, 34.0, 'gato', True, 34.56]
suma de mi_lista2 y mi_lista3:  [12, 34, 56, 67, 87, 65, 45.0, 12, 34.0, 'gato', True, 34.56]
mi_lista2 x 2:  [12, 34, 56, 67, 87, 65, 45.0, 12, 34, 56, 67, 87, 65, 45.0, 12, 34, 56, 67, 87, 65, 45.0]


OPERADORES ARITMÉTICOS BÁSICOS

In [ ]:
#operadores aritmeticos basicos
a=12.5
b=3
c=15
#suma
suma=a+b
#resta
resta=a-b
#producto
a*b
#division
a/b
#potencia
a**b
#modulo
a%b


#mini ejercicio: imprima los resultados de las operaciones anteriores

# errores numéricos
suma1=1+(1.5e56-1.5e56)
suma2=(1+1.5e56)-1.5e56
print(suma1)
print(suma2)

1.0
0.0


OPERADORES BÁSICOS DE COMPARACIÓN

In [ ]:
#operadores de comparacion basicos
a=12.5
b=3
c=15
#igual que
a==b
#diferente de
a!=b
#mayor que
a>b
#menor que
a<b
#mayor o igual
a>=b
#menor o igual
a<=b

#mini ejercicio: imprima el resultado de las comparaciones anteriores. qué tipo de variable es?


#otros operadores de comparación: https://www.tutorialspoint.com/python/python_basic_operators.htm

False

CICLOS FOR

In [ ]:
#ciclos con la función range
for i in range(10):
  print("i: ", i)

#mini ejercicio: mire la documentación de range (por ejemplo acá: https://www.w3schools.com/python/ref_func_range.asp)
# y haga que i vaya de -10 a 10 en pasos de 2.


#ciclos recorriendo listas o arreglos

lista4=[2,3,4,5,6.0,"gato"]
for elemento in lista4:
  print("elemento: ", elemento)



i:  0
i:  1
i:  2
i:  3
i:  4
i:  5
i:  6
i:  7
i:  8
i:  9
elemento:  2
elemento:  3
elemento:  4
elemento:  5
elemento:  6.0
elemento:  gato


NOTA IMPORTANTE!!! LA INDENTACIÓN SE UTILIZA PARA INDICAR QUÉ INSTRUCCIONES ESTÁN DENTRO DEL CICLO (O DENTRO DEL CONDICIONAL, O DENTRO DE LA FUNCION)...


In [ ]:
# mini ejercicio: pruebe los dos ciclos que están a continuación. Cuál es la diferencia?
for j in range(3):
  print("j: ", j)
  print("j+2: ", j+2) #nota: cuidado con el copy paste!!!!

for k in range(3):
  print("k: ", k)
print("k+2: ", k+2)

j:  0
j+2:  2
j:  1
j+2:  3
j:  2
j+2:  4
k:  0
k:  1
k:  2
k+2:  4


ARREGLOS DE NUMPY

In [ ]:

#numpy arrays

#import la librería de numpy para poder usar arreglos
import numpy as np

#genero un arreglo de ceros de 10 elementos:
arreglo=np.zeros(10)
print(arreglo)

#remplazo los ceros del arreglo por otro valor usando un ciclo (ver la celda de más adelante)
for i in range(10):
	arreglo[i]=(i-2)**3
print(arreglo)


#mini ejercicio: multiplique el arreglo por 3 e imprima el resultado. Qué diferencia hay con las listas?
mult=arreglo*3
print(mult)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ -8.  -1.   0.   1.   8.  27.  64. 125. 216. 343.]
[ -24.   -3.    0.    3.   24.   81.  192.  375.  648. 1029.]


SLICING DE ARREGLOS DE NUMPY

In [ ]:
print("todo", arreglo)
print("[1:3]", arreglo[1:3])
print("[:3]", arreglo[:3])
print("[3:]", arreglo[3:])
print("[-3:]", arreglo[-3:])
print("[3:-3]", arreglo[3: -3])
print("[3:-3: 2]", arreglo[3: -3: 2])

todo [ -8.  -1.   0.   1.   8.  27.  64. 125. 216. 343.]
[1:3] [-1.  0.]
[:3] [-8. -1.  0.]
[3:] [  1.   8.  27.  64. 125. 216. 343.]
[-3:] [125. 216. 343.]
[3:-3] [ 1.  8. 27. 64.]
[3:-3: 2] [ 1. 27.]


CONDICIONALES

In [ ]:
var1=17
var2=25
var3=13
lista_var=[12, 45, 17, 13]

#if else
if(var1>=var2):
	print(var1)
else:
	print(var2)

#if elif else
if(var1>=var3):
	print(var1)
elif(var2>=var3):
	print(var2)
else:
	print(var3)


# or y and

if(var1>var3 and var2>var3):
	print(var3)

if(var1<var3 or var2<var3):
	print(var3)


# in y not
if(var1 in lista_var):
	print("verdadero")


if(var2 not in lista_var):
	print("falso")


WHILE

In [ ]:
#while

j=10

while(j<120):
	print(j)
	#ojo:
	j+=15

FUNCIONES

In [ ]:
#defino una función que llamo mi_funcion. Uso la indentación para indicar qué está dentro de mi función
def mi_funcion(parametro1, parametro2):
  #la función imprime el parametro1
  f=17
  print("parametro1= ", parametro1)
  #la función retorna el parametro2
  return parametro2**2


#llamo mi mi funcion con los valores 3 y 4 y almaceno lo que retorna mi_funcion en la variable resultado
resultado=mi_funcion(3,4)
print("resultado", resultado)

#mini ejercicio: prueben qué pasa si quieren imprimir la variable parametro2 por fuera de la función

parametro1=  3
resultado 16


++++++++++++++++++++++++++++++++++++++++++ EJERCICIOS
 ++++++++++++++++++++++++++++++++++++++++++

EJERCICIO 1:

In [ ]:
#ejercicio 1

print("ejercicio 1")

#a) Inicializar dos variables globales (con valores escogidos por ustedes), una entera y otra flotante.\\


#b) Imprimir los valores de las variables en un mensaje: #
#"la primera tiene un valor de XX y la segunda variable tiene un valor de YY"



#c) Calcular el valor de la segunda variable dividida por la primera e imprimir : "El resultado es ZZ"



#d) Crear una lista con los elementos: 101, 26, rio, gato, 17, 45 y 28 e imprimirla.


#e) Agregarle a esa lista los elementos: 257, 285, 583


#f) Hacer un ciclo para recorrer dicha lista e imprimir sus elementos.


#g) imprimir el cuarto elemento de la lista.


#h) Calcular la longitud de la lista e imprimir: "la longitud de la lista es XX" puede usar le función len()



ejercicio 1


EJERCICIO 2:

In [ ]:
# Complete el siguiente código para que:
# recorra el arreglo `x`
# imprima los números impares
# y pare de imprimir al encontrar un número mayor a 700

import numpy as np

#genero un arreglo de número aleatorios:
x=np.int_(np.random.random(100)*900)
print("arreglo x: ", x)




arreglo x:  [228 573 591 199  78 215 293 635 836 584 504 118  11 178 610 854 546 146
 694  91 541 299 497 626 399 867 381  34 771 201 484 675 246 137 301 438
 294 395 761 388 304 845 515 889 178 192 739 217 850 325 600 340  64 731
 753  85  68 637 835 386 538 384 280 145 547 578 586 124 875 580 120 211
 208 166  26 757  18 603 835 477 246  48 774 723 340 424 866 847 141 700
 445 415 603 847 557 430 680 434 661 668]


EJERCICIO 3:

In [ ]:
#ejercicio 3
print("ejercicio 3")

#Haga una función llamada multiplicación
#que reciba como argumentos dos variables a y b y retorne a*b.
#Imprima lo que retorna la función para a=10 y b=18



ejercicio 3


EJERCICIO 4

In [ ]:
#ejercicio 4
print("ejercicio 4")
# Complete el siguiente código para que:
# recorra la lista x del ejercicio 2 y encuentre el mínimo de los elementos de la lista.
#Compare su resultado con el obtenido por np.min e imprima un mensajito con ambos valores.



ejercicio 4


EJERCICIO 5

In [ ]:
#ejercicio 5
print("ejercicio 5")
#  sin usar ciclos, sume los 10 primeros elementos del arreglo x a los 10 últimos elementos del arreglo x. Imprima el arreglo resultante.
import numpy as np

#genero un arreglo de número aleatorios:
x=np.int_(np.random.random(100)*900)
print("arreglo x: ", x)


ejercicio 5
arreglo x:  [281 106 481 257 616 494 418 316 511 154 697 772 287 659 689 128 643 520
 488 652 333 445 592 892 488 418 145 850 569 505 787 536 242 297 106 151
 772  26  15 126 608 860 479 140  70 600 357 175 572 148 406 794  32 802
 658 844 494 307 333 296 472 166 217 456 414 729 110 542 115 493 716 732
 398 544 166 332 277  58 239 532 696 437 245 100 688 267 287 460 299 166
 811 790  35 844 602 250 818 729  99 150]
